<a href="https://colab.research.google.com/github/kwmir113/Data-Science-Academy/blob/main/Copy_of_Kamran_Mir_Certificate_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
# 1. Loading CSV data from the URL below
url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRyoYQ2QDFmRZVgAJVQdAzQ0ZQQ7WoRgVrzqdGeGqLN_37T9TXxYzEdImfdFAdXU9Ky73q-K88bmfTc/pub?gid=0&single=true&output=csv'
df = pd.read_csv(url)

In [ ]:
#2 Shape of a dataframe
df.shape

(2000, 20)

In [ ]:
# 3. Head and Tail of the Data frame
df.head(n=10)
df.tail(n=10)

,SupplyChainId,Category,SubCategory,ProductId,ProductName,Description,Price,Quantity,ShippingCost,DeliveryTime,SellerId,SellerName,SellerCountry,SellerRating,SellerFeedback,OrderNumber,OrderId,OrderStatus,OrderDate,CustomerId
1990,127,Outdoors,Board Games,107,Sofa,Apple iPhone 11 64GB,11.99,2,5,2,169,Tom Doe,Indonesia,4.9,98,20,12363,Shipped,########,352
1991,141,Clothing,Televisions,115,Nike Pegasus,Dewalt 18 Volt Drill,599.00,2,8,2,160,Tom Doe,Canada,4.9,85,11,12347,Cancelled,########,351
1992,134,Electronics,Televisions,114,Waffle Maker,Keurig K-Cup Coffee Maker,2199.00,1,8,2,170,Jane Doe,Mexico,4.9,95,9,12355,Cancelled,########,362
1993,137,Sports,Phones,115,Monopoly,Michelin Primacy Tires,11.99,1,8,2,162,John Doe,Israel,4.8,90,2,12355,Shipped,########,351
1994,141,Furniture,Beverages,112,Coffee Maker,Dewalt 18 Volt Drill,400.00,3,5,3,164,Emily Doe,Italy,4.9,98,6,12345,Cancelled,########,362
1995,137,Beauty,Tools,108,Barbie,Barbie Dreamhouse Playset,120.00,1,5,2,173,James Doe,Germany,4.9,98,14,12357,Cancelled,########,363
1996,136,Electronics,Office Supplies,115,Monopoly,Dewalt 18 Volt Drill,799.00,1,6,2,157,Sarah Doe,France,4.9,98,9,12355,Cancelled,########,356
1997,141,Automotive,Bottoms,106,Tent,1 Carat Diamond Necklace,599.00,3,6,1,167,Noah Doe,China,4.9,98,2,12361,Shipped,########,364
1998,126,Clothing,Camping,110,Monopoly,Keurig K-Cup Coffee Maker,15.00,2,6,3,170,David Doe,Germany,4.9,85,10,12347,Delivered,########,348
1999,134,Beauty,Appliances,114,Barbie,Apple iPhone 11 64GB,19.99,1,10,1,157,Jane Doe,Spain,4.9,98,3,12352,Shipped,########,354

In [ ]:
# 4. data types of the columns
df.dtypes

SupplyChainId       int64
Category           object
SubCategory        object
ProductId           int64
ProductName        object
Description        object
Price             float64
Quantity            int64
ShippingCost        int64
DeliveryTime        int64
SellerId            int64
SellerName         object
SellerCountry      object
SellerRating      float64
SellerFeedback      int64
OrderNumber         int64
OrderId             int64
OrderStatus        object
OrderDate          object
CustomerId          int64
dtype: object

In [ ]:
# 5. Getting column names
df.columns.tolist()

['SupplyChainId',
 'Category',
 'SubCategory',
 'ProductId',
 'ProductName',
 'Description',
 'Price',
 'Quantity',
 'ShippingCost',
 'DeliveryTime',
 'SellerId',
 'SellerName',
 'SellerCountry',
 'SellerRating',
 'SellerFeedback',
 'OrderNumber',
 'OrderId',
 'OrderStatus',
 'OrderDate',
 'CustomerId']

In [ ]:
# 6. Summary stats
df.describe()

,SupplyChainId,ProductId,Price,Quantity,ShippingCost,DeliveryTime,SellerId,SellerRating,SellerFeedback,OrderNumber,OrderId,CustomerId
count,2000.000000,2000.000000,2000.00000,2000.0000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000
mean,132.346500,110.583500,262.52698,2.2905,7.203500,1.959500,166.407500,4.867300,88.159000,10.44550,12354.192500,354.750500
std,5.817591,5.872927,522.46217,1.0889,2.414747,0.768215,5.690574,0.060519,7.709243,5.83987,5.762469,5.921045
min,123.000000,101.000000,5.99000,1.0000,5.000000,1.000000,157.000000,4.700000,75.000000,1.00000,12345.000000,345.000000
25%,127.000000,106.000000,19.99000,1.0000,5.000000,1.000000,162.000000,4.800000,80.000000,5.00000,12349.000000,350.000000
50%,132.000000,110.000000,50.00000,2.0000,7.000000,2.000000,167.000000,4.900000,90.000000,11.00000,12354.000000,355.000000
75%,138.000000,116.000000,150.00000,3.0000,8.000000,3.000000,171.000000,4.900000,95.000000,16.00000,12359.000000,360.000000
max,142.000000,120.000000,2199.00000,4.0000,15.000000,3.000000,176.000000,4.900000,98.000000,20.00000,12364.000000,364.000000

In [ ]:
# 7. Checking NA values in columns
df.isna().sum()

SupplyChainId     0
Category          0
SubCategory       0
ProductId         0
ProductName       0
Description       0
Price             0
Quantity          0
ShippingCost      0
DeliveryTime      0
SellerId          0
SellerName        0
SellerCountry     0
SellerRating      0
SellerFeedback    0
OrderNumber       0
OrderId           0
OrderStatus       0
OrderDate         0
CustomerId        0
dtype: int64

In [ ]:
# 8. Selecting columns with data type as object
df.select_dtypes(include = 'object').columns

Index(['Category', 'SubCategory', 'ProductName', 'Description', 'SellerName',
       'SellerCountry', 'OrderStatus', 'OrderDate'],
      dtype='object')

In [ ]:
# 8.1 Selecting columns with data type as non object
df.select_dtypes(exclude = 'object').columns

Index(['SupplyChainId', 'ProductId', 'Price', 'Quantity', 'ShippingCost',
       'DeliveryTime', 'SellerId', 'SellerRating', 'SellerFeedback',
       'OrderNumber', 'OrderId', 'CustomerId'],
      dtype='object')

In [ ]:
# 9. Getting Occurrences in column SupplyChainId
df['SupplyChainId'].value_counts(ascending=True)

SupplyChainId
135     77
128     78
127     81
133     82
134     84
142     85
141     92
138     94
137     95
123     98
130    100
136    106
125    107
132    108
131    109
124    110
139    115
140    122
129    123
126    134
Name: count, dtype: int64

In [ ]:
# 1. Loading CSV data from the URL below
import pandas as pd

url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRyoYQ2QDFmRZVgAJVQdAzQ0ZQQ7WoRgVrzqdGeGqLN_37T9TXxYzEdImfdFAdXU9Ky73q-K88bmfTc/pub?gid=0&single=true&output=csv'
df = pd.read_csv(url)
df['OrderStatus'].value_counts(ascending=True)

OrderStatus
Shipped      418
Returned     461
Delivered    476
Cancelled    645
Name: count, dtype: int64

In [ ]:
df['SellerName'].value_counts(ascending=True)

SellerName
Mia Doe           73
Isabella Doe      84
Jack Doe          85
Emma Doe          89
Noah Doe          93
Elizabeth Doe     94
Olivia Doe        97
Sophia Doe        97
David Doe         99
John Doe          99
Emily Doe        100
Sarah Doe        103
Mark Doe         103
Oliver Doe       103
Jane Doe         106
Ava Doe          109
Tom Doe          116
William Doe      119
James Doe        231
Name: count, dtype: int64

In [ ]:
# 11. Create a new DataFrame with Specific Columns
data = data = {
    'Category', 'SubCategory', 'ProductId', 'ProductName', 'Description', 'Price', 'Quantity', 'ShippingCost', 'DeliveryTime', 'SellerID'
}
df = pd.DataFrame(data)
print(df)

              0
0   Description
1   ProductName
2         Price
3      SellerID
4  DeliveryTime
5     ProductId
6   SubCategory
7  ShippingCost
8      Quantity
9      Category

In [ ]:
# 12. Getting unique name in a column
df[df['SellerCountry'] == 'Italy']

,SupplyChainId,Category,SubCategory,ProductId,ProductName,Description,Price,Quantity,ShippingCost,DeliveryTime,SellerId,SellerName,SellerCountry,SellerRating,SellerFeedback,OrderNumber,OrderId,OrderStatus,OrderDate,CustomerId
2,128,Beauty,Phones,112,Printer,Optimum Nutrition Protein Powder,80.00,2,5,2,158,Sarah Doe,Italy,4.8,85,12,12356,Cancelled,########,349
50,123,Electronics,Small Appliances,115,Drill,Ashley Furniture Sofa,120.00,1,8,1,168,Isabella Doe,Italy,4.7,90,2,12350,Cancelled,########,354
59,140,Games,Small Appliances,117,Foundation,Ashley Furniture Sofa,19.00,2,6,3,169,William Doe,Italy,4.9,75,2,12351,Returned,########,361
79,136,Clothing,Necklaces,118,Coffee Maker,Levis 511 Slim Fit Jeans,19.99,3,5,3,157,Sarah Doe,Italy,4.7,95,3,12362,Cancelled,########,360
86,142,Books,Parts,103,Yoga Pants,Keurig K-Cup Coffee Maker,120.00,2,5,1,172,Sarah Doe,Italy,4.9,90,17,12347,Delivered,########,349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1930,139,Shoes,Supplements,114,Jeans,Ashley Furniture Sofa,5.99,4,15,2,175,Sophia Doe,Italy,4.9,85,6,12346,Cancelled,########,364
1974,136,Shoes,Parts,105,Soda,Apple iPhone 11 64GB,19.00,2,8,2,170,Jack Doe,Italy,4.8,80,16,12354,Cancelled,########,357
1981,140,Jewelry,Bottoms,113,Diamond Necklace,Barbie Dreamhouse Playset,100.00,2,7,1,173,James Doe,Italy,4.9,90,16,12345,Delivered,########,355
1982,126,Beauty,Office Supplies,120,Tires,Barbie Dreamhouse Playset,35.00,4,15,3,176,Mark Doe,Italy,4.9,98,19,12348,Cancelled,########,352
1994,141,Furniture,Beverages,112,Coffee Maker,Dewalt 18 Volt Drill,400.00,3,5,3,164,Emily Doe,Italy,4.9,98,6,12345,Cancelled,########,362

In [ ]:
# 1. Loading CSV data from the URL below
import pandas as pd

url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRyoYQ2QDFmRZVgAJVQdAzQ0ZQQ7WoRgVrzqdGeGqLN_37T9TXxYzEdImfdFAdXU9Ky73q-K88bmfTc/pub?gid=0&single=true&output=csv'
df = pd.read_csv(url)

In [ ]:
# 13. Find rows where SellerCountry is US and the Price is > 100
df [(df['SellerCountry'] == 'US') & (df['Price'] > 100)]

,SupplyChainId,Category,SubCategory,ProductId,ProductName,Description,Price,Quantity,ShippingCost,DeliveryTime,SellerId,SellerName,SellerCountry,SellerRating,SellerFeedback,OrderNumber,OrderId,OrderStatus,OrderDate,CustomerId
4,132,Shoes,Camping,120,Harry Potter,Keurig K-Cup Coffee Maker,2199.0,2,8,2,160,James Doe,US,4.9,98,18,12346,Cancelled,########,359
95,142,Beauty,Phones,115,Drill,Ashley Furniture Sofa,120.0,3,7,3,163,Emma Doe,US,4.9,75,9,12357,Cancelled,########,359
298,138,Electronics,Beverages,105,Harry Potter,Keurig K-Cup Coffee Maker,400.0,1,5,1,164,Ava Doe,US,4.9,95,17,12349,Delivered,########,359
359,135,Clothing,Living Room,117,Yoga Pants,Cuisinart Belgian Waffle Maker,2199.0,2,5,3,162,Sophia Doe,US,4.9,90,10,12345,Delivered,########,350
395,125,Books,Supplements,104,Tent,Cuisinart Belgian Waffle Maker,400.0,2,6,1,174,Jane Doe,US,4.8,95,18,12349,Returned,########,356
492,140,Appliances,Televisions,107,Yoga Pants,Ashley Furniture Sofa,120.0,4,8,2,170,Mark Doe,US,4.7,80,6,12345,Delivered,########,361
737,140,Jewelry,Living Room,108,Yoga Pants,Keurig K-Cup Coffee Maker,599.0,3,5,1,161,Jane Doe,US,4.9,90,12,12364,Cancelled,########,351
799,123,Sports,Running Shoes,118,Yoga Pants,Hasbro Monopoly Game,120.0,4,7,1,175,Oliver Doe,US,4.9,75,14,12356,Delivered,########,355
847,126,Toys,Beverages,118,Nike Pegasus,Levis 511 Slim Fit Jeans,120.0,1,5,1,164,Isabella Doe,US,4.9,95,9,12346,Returned,########,350
1135,140,Clothing,Televisions,101,iPhone 11,Nike Pegasus 36 Running Shoes,120.0,1,5,2,158,Jack Doe,US,4.7,75,12,12354,Cancelled,########,353
1155,127,Health,Small Appliances,110,Nike Pegasus,Ashley Furniture Sofa,799.0,3,8,1,164,James Doe,US,4.9,90,3,12362,Delivered,########,364
1174,125,Shoes,Office Supplies,110,Waffle Maker,50 inch LED 4K Ultra HD TV,400.0,2,15,1,170,James Doe,US,4.9,90,14,12359,Cancelled,########,362
1264,125,Automotive,Athletic Wear,111,Monopoly,Michelin Primacy Tires,2199.0,2,10,2,157,Olivia Doe,US,4.9,90,2,12346,Delivered,########,350
1441,138,Toys,Parts,111,Spiderman,Dewalt 18 Volt Drill,599.0,1,5,1,164,James Doe,US,4.9,75,12,12349,Cancelled,########,364
1491,129,Electronics,Phones,118,Soda,Spiderman Action Figure,599.0,2,8,1,160,Sophia Doe,US,4.9,85,17,12355,Cancelled,########,362
1507,125,Sports,Small Appliances,118,Sofa,1 Carat Diamond Necklace,599.0,3,5,3,173,Elizabeth Doe,US,4.9,90,11,12345,Shipped,########,362
1537,126,Electronics,Camping,108,Waffle Maker,Apple iPhone 11 64GB,2199.0,3,7,3,175,Ava Doe,US,4.8,95,10,12358,Delivered,########,364
1541,136,Jewelry,Televisions,112,Sony Bravia,50 inch LED 4K Ultra HD TV,150.0,2,10,1,157,Isabella Doe,US,4.8,95,19,12363,Cancelled,########,351
1635,131,Beauty,Living Room,110,Jeans,Pepsi 12 Pack,799.0,1,8,2,173,Jane Doe,US,4.9,90,2,12354,Returned,########,347
1648,131,Appliances,Necklaces,101,Foundation,1 Carat Diamond Necklace,400.0,4,6,3,166,James Doe,US,4.9,90,19,12358,Shipped,########,364
1697,123,Books,Board Games,109,Sofa,50 inch LED 4K Ultra HD TV,400.0,3,6,2,169,Oliver Doe,US,4.9,90,13,12356,Delivered,########,362
1866,126,Home Improvement,Office Supplies,101,Tires,Nike Pegasus 36 Running Shoes,2199.0,4,10,1,174,James Doe,US,4.9,75,2,12360,Shipped,########,352
1906,134,Toys,Action Figures,112,Soda,Hasbro Monopoly Game,599.0,1,7,1,175,William Doe,US,4.8,75,8,12361,Cancelled,########,362
1971,135,Electronics,Athletic Wear,108,Diamond Necklace,90 Degree By Reflex Yoga Pants,599.0,1,10,1,165,Emily Doe,US,4.9,95,3,12362,Delivered,########,359

In [ ]:
# 14. Select rows where Category is "Beauty" or "Health"
df[(df['Category'] == 'Beauty') | (df['Category'] == 'Health') ]

,SupplyChainId,Category,SubCategory,ProductId,ProductName,Description,Price,Quantity,ShippingCost,DeliveryTime,SellerId,SellerName,SellerCountry,SellerRating,SellerFeedback,OrderNumber,OrderId,OrderStatus,OrderDate,CustomerId
2,128,Beauty,Phones,112,Printer,Optimum Nutrition Protein Powder,80.00,2,5,2,158,Sarah Doe,Italy,4.8,85,12,12356,Cancelled,########,349
3,133,Health,Athletic Wear,115,Monopoly,Keurig K-Cup Coffee Maker,45.00,4,10,2,165,Sarah Doe,India,4.7,95,8,12346,Cancelled,########,354
6,124,Beauty,Appliances,109,Yoga Pants,Keurig K-Cup Coffee Maker,11.99,2,8,1,163,Ava Doe,Australia,4.9,95,6,12351,Shipped,########,353
32,123,Beauty,Running Shoes,106,Soda,Nike Pegasus 36 Running Shoes,19.99,1,8,2,160,Sophia Doe,Australia,4.7,90,12,12347,Delivered,########,353
65,124,Health,Board Games,114,Nike Pegasus,Optimum Nutrition Protein Powder,11.99,1,7,1,168,Sophia Doe,Russia,4.9,95,9,12354,Cancelled,########,347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1982,126,Beauty,Office Supplies,120,Tires,Barbie Dreamhouse Playset,35.00,4,15,3,176,Mark Doe,Italy,4.9,98,19,12348,Cancelled,########,352
1985,138,Health,Athletic Wear,105,Harry Potter,Dewalt 18 Volt Drill,99.99,1,6,2,164,Jack Doe,Australia,4.9,98,5,12360,Delivered,########,348
1987,132,Beauty,Tools,112,Drill,Barbie Dreamhouse Playset,2199.00,4,5,2,159,Jane Doe,Russia,4.9,85,12,12347,Returned,########,360
1995,137,Beauty,Tools,108,Barbie,Barbie Dreamhouse Playset,120.00,1,5,2,173,James Doe,Germany,4.9,98,14,12357,Cancelled,########,363
1999,134,Beauty,Appliances,114,Barbie,Apple iPhone 11 64GB,19.99,1,10,1,157,Jane Doe,Spain,4.9,98,3,12352,Shipped,########,354

In [ ]:
# 1. Loading CSV data from the URL below
import pandas as pd

url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRyoYQ2QDFmRZVgAJVQdAzQ0ZQQ7WoRgVrzqdGeGqLN_37T9TXxYzEdImfdFAdXU9Ky73q-K88bmfTc/pub?gid=0&single=true&output=csv'
df = pd.read_csv(url)

In [2]:
# 1. Loading CSV data from the URL below
import pandas as pd

url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRyoYQ2QDFmRZVgAJVQdAzQ0ZQQ7WoRgVrzqdGeGqLN_37T9TXxYzEdImfdFAdXU9Ky73q-K88bmfTc/pub?gid=0&single=true&output=csv'
df = pd.read_csv(url)

In [4]:
# 15. Shipping cost under 10, SellerFeedback > 95
df['SellerFeedback'] = pd.to_numeric(df['SellerFeedback'], errors='coerce')
filtered_df = df[(df['ShippingCost'] <= 10) & (df['SellerFeedback'] > 95)]
filtered_df

,SupplyChainId,Category,SubCategory,ProductId,ProductName,Description,Price,Quantity,ShippingCost,DeliveryTime,SellerId,SellerName,SellerCountry,SellerRating,SellerFeedback,OrderNumber,OrderId,OrderStatus,OrderDate,CustomerId
4,132,Shoes,Camping,120,Harry Potter,Keurig K-Cup Coffee Maker,2199.00,2,8,2,160,James Doe,US,4.9,98,18,12346,Cancelled,########,359
10,137,Shoes,Makeup,107,Tent,50 inch LED 4K Ultra HD TV,5.99,2,10,1,165,Tom Doe,Canada,4.9,98,19,12359,Cancelled,########,351
22,130,Books,Running Shoes,113,Yoga Pants,Barbie Dreamhouse Playset,50.00,1,5,3,160,James Doe,Japan,4.9,98,15,12354,Returned,########,348
23,128,Toys,Board Games,111,Nike Pegasus,50 inch LED 4K Ultra HD TV,5.99,1,5,1,175,Olivia Doe,Australia,4.9,98,13,12352,Cancelled,########,361
48,139,Automotive,Beverages,102,Drill,Michelin Primacy Tires,11.99,4,10,2,173,Elizabeth Doe,UK,4.8,98,12,12361,Cancelled,########,346
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,141,Furniture,Beverages,112,Coffee Maker,Dewalt 18 Volt Drill,400.00,3,5,3,164,Emily Doe,Italy,4.9,98,6,12345,Cancelled,########,362
1995,137,Beauty,Tools,108,Barbie,Barbie Dreamhouse Playset,120.00,1,5,2,173,James Doe,Germany,4.9,98,14,12357,Cancelled,########,363
1996,136,Electronics,Office Supplies,115,Monopoly,Dewalt 18 Volt Drill,799.00,1,6,2,157,Sarah Doe,France,4.9,98,9,12355,Cancelled,########,356
1997,141,Automotive,Bottoms,106,Tent,1 Carat Diamond Necklace,599.00,3,6,1,167,Noah Doe,China,4.9,98,2,12361,Shipped,########,364
1999,134,Beauty,Appliances,114,Barbie,Apple iPhone 11 64GB,19.99,1,10,1,157,Jane Doe,Spain,4.9,98,3,12352,Shipped,########,354

In [ ]:
# 16 Rename a column
df = df.rename(columns={'SellerFeedback': 'ReviewRating'})
df.columns.tolist()

['SupplyChainId',
 'Category',
 'SubCategory',
 'ProductId',
 'ProductName',
 'Description',
 'Price',
 'Quantity',
 'ShippingCost',
 'DeliveryTime',
 'SellerId',
 'SellerName',
 'SellerCountry',
 'SellerRating',
 'ReviewRating',
 'OrderNumber',
 'OrderId',
 'OrderStatus',
 'OrderDate',
 'CustomerId']

In [ ]:
# 17 Calculate Total Sales for a Category
category_sales = df.groupby('Category')['Quantity'].sum()
print(category_sales)

Category
Appliances          232
Automotive          250
Beauty              206
Books               238
Clothing            306
Electronics         389
Furniture           233
Games               182
Grocery             225
Health              253
Home Improvement    241
Jewelry             235
Kitchen             156
Office              242
Outdoors            236
Shoes               258
Sports              268
Toys                431
Name: Quantity, dtype: int64

In [ ]:
# 17 Calculate total number of Sales in a Category
Category_Total = df[df['Category'] == 'Home Improvement']['Quantity'].sum()
print(f"Total Home Improvement items: {Category_Total}")

Total Home Improvement items: 241

In [ ]:
# 18 Find out average Shipping Cost
avg_shipping_cost = df['ShippingCost'].mean()
print(f"Average Shipping Cost: ${avg_shipping_cost:.2f}")

Average Shipping Cost: $7.20

In [ ]:
#19 Sum and Count Prices for Beauty Products from China
sum_beautyProduct_China = df[(df['Category'] == 'Beauty') & (df['SellerCountry'] == 'China')]['Price'].sum()

print(f"Total Price for Beauty products from China: ${beauty_china_sum:.2f}")

In [ ]:
#19 Sum and Count Prices for Beauty Products from China
sum_beautyProduct_China = df[(df['Category'] == 'Beauty') & (df['SellerCountry'] == 'China')]['Price'].sum()

print(f"Total Price for Beauty products from China: ${beauty_china_sum:.2f}")

In [ ]:
#19 Sum and Count Prices for Beauty Products from China
sum_beautyProduct_China = df[(df['Category'] == 'Beauty') & (df['SellerCountry'] == 'China')]['Price'].sum()

print(f"Total Price for Beauty products from China: ${sum_beautyProduct_China:.2f}")

Total Price for Beauty products from China: $145.99

In [ ]:
# 20 Add a new Column with Null values
import numpy as np
df['NewColumn'] = np.nan
df.isna().sum()

SupplyChainId       0
Category            0
SubCategory         0
ProductId           0
ProductName         0
Description         0
Price               0
Quantity            0
ShippingCost        0
DeliveryTime        0
SellerId            0
SellerName          0
SellerCountry       0
SellerRating        0
ReviewRating        0
OrderNumber         0
OrderId             0
OrderStatus         0
OrderDate           0
CustomerId          0
NewColumn        2000
dtype: int64

In [ ]:
# 21 List average price by sub category
electronics_avg_price = df[df['Category'] == 'Electronics'].groupby('SubCategory')['Price'].mean().reset_index()
electronics_avg_price.columns = ['SubCategory', 'AveragePrice']
print(electronics_avg_price)

         SubCategory  AveragePrice
0     Action Figures    152.924286
1         Appliances    183.898000
2      Athletic Wear    838.536923
3          Beverages     86.621250
4        Board Games    563.995000
5            Bottoms    137.000000
6            Camping    328.663333
7              Dolls     51.496250
8            Fiction    337.831667
9        Living Room    154.284286
10            Makeup    414.831667
11         Necklaces    829.427143
12   Office Supplies    189.138571
13             Parts    137.998000
14            Phones    273.615385
15     Running Shoes    257.497000
16  Small Appliances     59.747500
17       Supplements    328.748750
18       Televisions    372.999091
19             Tools     49.796000

In [ ]:
# 22 Filter by Delivery time and quantity
filtered_data = df[(df['DeliveryTime'] <= 5) & (df['Quantity'] > 10)]
# Display the filtered rows
filtered_data

Empty DataFrame
Columns: [SupplyChainId, Category, SubCategory, ProductId, ProductName, Description, Price, Quantity, ShippingCost, DeliveryTime, SellerId, SellerName, SellerCountry, SellerRating, ReviewRating, OrderNumber, OrderId, OrderStatus, OrderDate, CustomerId, NewColumn]
Index: []

[0 rows x 21 columns]

In [ ]:
# Find the Maxiumu price among all products in the dataset
max_price = df['Price'].max()

print(f"Maximum price among all products: ${max_price:.2f}")

Maximum price among all products: $2199.00

In [ ]:
# 24 Find Total Sales per Seller
df['SalesAmount'] = df['Price'] * df['Quantity']
seller_sales = df.groupby('SellerId')['SalesAmount'].sum().reset_index()
# Display the results
print(seller_sales)

    SellerId  SalesAmount
0        157     60254.44
1        158     50925.66
2        159     91121.68
3        160     60917.56
4        161     44499.74
5        162     47704.39
6        163     58750.37
7        164     57117.44
8        165     72177.54
9        166     68218.66
10       167     65584.66
11       168     84543.43
12       169     53498.40
13       170     42233.75
14       171     43619.46
15       172     38966.48
16       173     59585.33
17       174     54697.61
18       175     52174.71
19       176     50123.60

In [ ]:
# 25 Filter products with "Shoes" in the description
shoes_products = df[df['Description'].str.contains('Shoes', case=False, na=False)]

# Display the filtered rows
shoes_products

,SupplyChainId,Category,SubCategory,ProductId,ProductName,Description,Price,Quantity,ShippingCost,DeliveryTime,...,SellerCountry,SellerRating,ReviewRating,OrderNumber,OrderId,OrderStatus,OrderDate,CustomerId,NewColumn,SalesAmount
25,132,Appliances,Televisions,119,Tires,Nike Pegasus 36 Running Shoes,150.00,3,10,2,...,South Africa,4.9,85,6,12354,Cancelled,########,363,NaN,450.00
26,134,Clothing,Necklaces,120,Spiderman,Nike Pegasus 36 Running Shoes,599.00,1,5,2,...,South Africa,4.9,90,8,12362,Returned,########,361,NaN,599.00
32,123,Beauty,Running Shoes,106,Soda,Nike Pegasus 36 Running Shoes,19.99,1,8,2,...,Australia,4.7,90,12,12347,Delivered,########,353,NaN,19.99
41,139,Home Improvement,Necklaces,107,Sony Bravia,Nike Pegasus 36 Running Shoes,80.00,2,5,1,...,UK,4.8,90,18,12354,Cancelled,########,353,NaN,160.00
49,129,Automotive,Action Figures,112,Barbie,Nike Pegasus 36 Running Shoes,400.00,1,6,3,...,Mexico,4.9,90,6,12348,Shipped,########,362,NaN,400.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1916,132,Health,Bottoms,108,Spiderman,Nike Pegasus 36 Running Shoes,45.00,3,5,1,...,Mexico,4.9,95,14,12355,Cancelled,########,356,NaN,135.00
1924,126,Shoes,Athletic Wear,118,Sofa,Nike Pegasus 36 Running Shoes,25.00,1,5,3,...,Canada,4.9,95,4,12348,Cancelled,########,353,NaN,25.00
1951,128,Clothing,Camping,113,Waffle Maker,Nike Pegasus 36 Running Shoes,50.00,4,8,3,...,Canada,4.9,98,17,12359,Cancelled,########,346,NaN,200.00
1967,123,Games,Dolls,119,Monopoly,Nike Pegasus 36 Running Shoes,45.00,3,5,1,...,South Africa,4.9,80,5,12355,Returned,########,360,NaN,135.00
1978,139,Home Improvement,Running Shoes,107,Waffle Maker,Nike Pegasus 36 Running Shoes,120.00,4,5,3,...,Israel,4.9,95,20,12350,Shipped,########,346,NaN,480.00