<a href="https://colab.research.google.com/github/kwmir113/Data-Science-Academy/blob/main/Copy_of_sql_Income_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
https://colab.research.google.com/#create=true

In [ ]:
# Code snippet 1
# Importing the income dataset
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/nvamsimohan/DallasDSA/refs/heads/main/Tarrant%20County%20Income%20Dataset%20SQL%20CSV.csv')
data

,Age,Workclass,Profile,Education,Marital_Status,Occupation,Relationship,Race,Gender,Capital_Gain,Capital_Loss,Hours_per_Week,Native_Country,Income
0,39,State-gov,77516,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
# Code snippet 2
# Importing sqlite3 package (to run SQL queries in Python)
import sqlite3
# Code snippet 3
# Creating a sample database as a connection
conn = sqlite3.connect('sample.db')

In [ ]:
# Code snippet 4
# Storing the pandas dataframe as a table in the sample database
data.to_sql('data_sql', conn)

32561

In [ ]:
# Code snippet 5
# Display all the data from the table
sql_query = ''' SELECT * FROM data_sql '''
data_output = pd.read_sql(sql_query, conn)
data_output

,index,Age,Workclass,Profile,Education,Marital_Status,Occupation,Relationship,Race,Gender,Capital_Gain,Capital_Loss,Hours_per_Week,Native_Country,Income
0,0,39,State-gov,77516,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,1,50,Self-emp-not-inc,83311,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,2,38,Private,215646,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,3,53,Private,234721,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,4,28,Private,338409,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,32556,27,Private,257302,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,32557,40,Private,154374,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,32558,58,Private,151910,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,32559,22,Private,201490,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,32560,52,Self-emp-inc,287927,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
# Code snippet 6
# Display all the data from the table where age > 50
sql_query = ''' SELECT * FROM data_sql WHERE age > 50 '''
data_output = pd.read_sql(sql_query, conn)
data_output

,index,Age,Workclass,Profile,Education,Marital_Status,Occupation,Relationship,Race,Gender,Capital_Gain,Capital_Loss,Hours_per_Week,Native_Country,Income
0,3,53,Private,234721,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
1,7,52,Self-emp-not-inc,209642,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
2,21,54,Private,302146,HS-grad,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
3,24,59,Private,109015,HS-grad,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
4,25,56,Local-gov,216851,Bachelors,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6455,32542,72,None,129912,HS-grad,Married-civ-spouse,None,Husband,White,Male,0,0,25,United-States,<=50K
6456,32548,65,Self-emp-not-inc,99359,Prof-school,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
6457,32554,53,Private,321865,Masters,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
6458,32558,58,Private,151910,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
6459,32560,52,Self-emp-inc,287927,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
# Code snippet 6
# Display all the data from the table where age <= 50
sql_query = ''' SELECT * FROM data_sql WHERE age <=50 '''
data_output = pd.read_sql(sql_query, conn)
data_output

,index,Age,Workclass,Profile,Education,Marital_Status,Occupation,Relationship,Race,Gender,Capital_Gain,Capital_Loss,Hours_per_Week,Native_Country,Income
0,0,39,State-gov,77516,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,1,50,Self-emp-not-inc,83311,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,2,38,Private,215646,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,4,28,Private,338409,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,5,37,Private,284582,Masters,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26096,32553,32,Private,116138,Masters,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
26097,32555,22,Private,310152,Some-college,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
26098,32556,27,Private,257302,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
26099,32557,40,Private,154374,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
26100,32559,22,Private,201490,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [ ]:
# Code snippet 7
# Display all the data from the table where age > 50
sql_query = ''' SELECT * FROM data_sql WHERE age > 50 '''
data_output = pd.read_sql(sql_query, conn)
data_output

,index,Age,Workclass,Profile,Education,Marital_Status,Occupation,Relationship,Race,Gender,Capital_Gain,Capital_Loss,Hours_per_Week,Native_Country,Income
0,3,53,Private,234721,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
1,7,52,Self-emp-not-inc,209642,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
2,21,54,Private,302146,HS-grad,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
3,24,59,Private,109015,HS-grad,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
4,25,56,Local-gov,216851,Bachelors,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6455,32542,72,None,129912,HS-grad,Married-civ-spouse,None,Husband,White,Male,0,0,25,United-States,<=50K
6456,32548,65,Self-emp-not-inc,99359,Prof-school,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
6457,32554,53,Private,321865,Masters,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
6458,32558,58,Private,151910,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
6459,32560,52,Self-emp-inc,287927,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
# Code snippet 8
# Display all the data from the table where age < 30 and marital status of never married
sql_query = ''' SELECT * FROM data_sql WHERE age < 30 AND Marital_Status = 'Never-married'   '''
data_output = pd.read_sql(sql_query, conn)
data_output

,index,Age,Workclass,Profile,Education,Marital_Status,Occupation,Relationship,Race,Gender,Capital_Gain,Capital_Loss,Hours_per_Week,Native_Country,Income
0,12,23,Private,122272,Bachelors,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
1,16,25,Self-emp-not-inc,176756,HS-grad,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
2,26,19,Private,168294,HS-grad,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
3,30,23,Local-gov,190709,Assoc-acdm,Never-married,Protective-serv,Not-in-family,White,Male,0,0,52,United-States,<=50K
4,31,20,Private,266015,Some-college,Never-married,Sales,Own-child,Black,Male,0,0,44,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7161,32524,26,Private,191648,Assoc-acdm,Never-married,Machine-op-inspct,Other-relative,White,Female,0,0,15,United-States,<=50K
7162,32527,22,Private,203715,Some-college,Never-married,Adm-clerical,Own-child,White,Male,0,0,40,United-States,<=50K
7163,32535,22,Private,325033,12th,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
7164,32555,22,Private,310152,Some-college,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
7165,32559,22,Private,201490,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [ ]:
# Code snippet 9
# Display all the data from the table where age < 30 and marital status as never married and with positive capital gains
sql_query = ''' SELECT * FROM data_sql WHERE age < 30 AND Marital_Status = 'Never-married' AND Capital_Gain > 0  '''
data_output = pd.read_sql(sql_query, conn)
data_output

,index,Age,Workclass,Profile,Education,Marital_Status,Occupation,Relationship,Race,Gender,Capital_Gain,Capital_Loss,Hours_per_Week,Native_Country,Income
0,106,17,None,304873,10th,Never-married,None,Own-child,White,Female,34095,0,32,United-States,<=50K
1,271,17,Private,191260,9th,Never-married,Other-service,Own-child,White,Male,1055,0,24,United-States,<=50K
2,421,17,Private,175024,11th,Never-married,Handlers-cleaners,Own-child,White,Male,2176,0,18,United-States,<=50K
3,598,25,Private,200408,Some-college,Never-married,Tech-support,Not-in-family,White,Male,2174,0,40,United-States,<=50K
4,613,26,Local-gov,208122,Bachelors,Never-married,Prof-specialty,Own-child,White,Male,1055,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,31320,24,Private,103064,Bachelors,Never-married,Tech-support,Not-in-family,White,Female,3674,0,40,United-States,<=50K
209,32048,21,Private,213015,HS-grad,Never-married,Handlers-cleaners,Other-relative,Black,Male,2176,0,40,United-States,<=50K
210,32051,22,Private,205940,Bachelors,Never-married,Adm-clerical,Own-child,White,Female,1055,0,30,United-States,<=50K
211,32155,23,Private,142766,Some-college,Never-married,Adm-clerical,Own-child,White,Male,1055,0,20,United-States,<=50K
212,32169,25,Private,149943,HS-grad,Never-married,Other-service,Other-relative,Asian-Pac-Islander,Male,4101,0,60,None,<=50K

In [ ]:
# Code snippet 9
# Display all the data from the table where age < 30 and marital status as never married and with positive capital gains
sql_query = ''' SELECT * FROM data_sql WHERE age < 30 AND Marital_Status = 'Never-married' AND Capital_Gain > 0  '''
data_output = pd.read_sql(sql_query, conn)
data_output

,index,Age,Workclass,Profile,Education,Marital_Status,Occupation,Relationship,Race,Gender,Capital_Gain,Capital_Loss,Hours_per_Week,Native_Country,Income
0,106,17,None,304873,10th,Never-married,None,Own-child,White,Female,34095,0,32,United-States,<=50K
1,271,17,Private,191260,9th,Never-married,Other-service,Own-child,White,Male,1055,0,24,United-States,<=50K
2,421,17,Private,175024,11th,Never-married,Handlers-cleaners,Own-child,White,Male,2176,0,18,United-States,<=50K
3,598,25,Private,200408,Some-college,Never-married,Tech-support,Not-in-family,White,Male,2174,0,40,United-States,<=50K
4,613,26,Local-gov,208122,Bachelors,Never-married,Prof-specialty,Own-child,White,Male,1055,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,31320,24,Private,103064,Bachelors,Never-married,Tech-support,Not-in-family,White,Female,3674,0,40,United-States,<=50K
209,32048,21,Private,213015,HS-grad,Never-married,Handlers-cleaners,Other-relative,Black,Male,2176,0,40,United-States,<=50K
210,32051,22,Private,205940,Bachelors,Never-married,Adm-clerical,Own-child,White,Female,1055,0,30,United-States,<=50K
211,32155,23,Private,142766,Some-college,Never-married,Adm-clerical,Own-child,White,Male,1055,0,20,United-States,<=50K
212,32169,25,Private,149943,HS-grad,Never-married,Other-service,Other-relative,Asian-Pac-Islander,Male,4101,0,60,None,<=50K